[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spice_program = "CcoYv1X4RczUmuGCUw3Vg1XWxspaofsh8dtD26cmN7nm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=7f2a3c15-9d37-4850-a525-2aab028411bf"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
